name: VoltNetwork
version: '${project.version}'
main: me.tony.main.voltnetwork.VoltNetwork
api-version: '1.21'

softdepend:
  - DecentHolograms

commands:
  voltcustomenchant:
    description: Custom Enchantment Main Command
    aliases:
      - vce
  config:
    description: Configuration Main Command
    aliases:
      - cfg
  gravestone:
    description: Gravestone debug command.
  koth:
    description: Main Koth Command
  staffchat:
    description: Staff Chat Command
    aliases:
      - sc
  dono:
    description: Donator Perks Command
  nv:
    description: Donator Night Vision Perk
  staffmode:
    description: Staff Mode Commands
    aliases:
      - sm
  item:
    description: Display your Cool item
  cooldown:
    desription: Cooldown Command
    aliases:
      - cd
      - cooldowns